
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_EnemyIA from "./scripts/EnemyIA";
import * as scripts_EnemySpawner from "./scripts/EnemySpawner";
import * as scripts_moving from "./scripts/moving";

export const scriptsMap = {
    "scripts/EnemyIA.ts": scripts_EnemyIA,
	"scripts/EnemySpawner.ts": scripts_EnemySpawner,
	"scripts/moving.ts": scripts_moving
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
